version: '3.9'

services:

  postgres-integration:
    container_name: postgres-integration
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=energy_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.52
            
  rabbitmq-integration:
    container_name: rabbitmq-integration
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.55
                
  redis-integration:
    container_name: redis-integration
    image: redis:7.0
    ports:
      - "6379:6379"
    restart: always
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.56
         
  django-integration:
    container_name: django-integration
    build: 
        context: ./
        dockerfile: ./DS2022_30441_Filip_Denisa_1_Backend/Dockerfile
    restart: always
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=energy_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=postgres-integration
      - POSTGRES_PORT=5432
    depends_on:
      - postgres-integration
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.53
            
  envoy-proxy:
    container_name: envoy-proxy
    image: envoyproxy/envoy-dev:4634ffdf32752e70a4186fcaf269dca8ff004395 
    ports:
      - "9901:9901"
      - "10000:10000"
      - "8080:8080"
    restart: always
    command: envoy -c /home/envoy.yaml
    volumes:
      - ./DS2022_30441_Filip_Denisa_1_Frontend/energy_platform/envoy.yaml:/home/envoy.yaml
      
  grpc-server-integration:
    container_name: grpc-server-integration
    build:
      context: ./   
      dockerfile: ./DS2022_30441_Filip_Denisa_1_Backend/energy_platform/grpc_gen/Dockerfile 
    command: python grpc_server.py
    ports:
        - "50051:50051"
    restart: always
    
  angular-integration:
    container_name: angular-integration
    build:
      context: ./
      dockerfile: ./DS2022_30441_Filip_Denisa_1_Frontend/energy_platform/Dockerfile 
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - envoy-proxy
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.54
   

volumes:
    postgres-integration:
        driver:
            local
    django-integration:
        driver:
            local
    angular-integration:
        driver:
            local

networks:
  assignment1-network:
    external: true