version: '3.9'

services:

  postgres-integration:
    container_name: postgres-integration
    image: postgres
    #command: >
    #  bash -c "psql -U postgres
    #  && CREATE DATABASE energy_platform;"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=energy_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.52
         
  django-integration:
    container_name: django-integration
    build: 
        context: ./
        dockerfile: ./DS2022_30441_Filip_Denisa_1_Backend/Dockerfile
    restart: always
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=energy_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=postgres-integration
      - POSTGRES_PORT=5432
    depends_on:
      - postgres-integration
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.53
    
  angular-integration:
    container_name: angular-integration
    build:
      context: ./
      dockerfile: ./DS2022_30441_Filip_Denisa_1_Frontend/energy_platform/Dockerfile 
    restart: always
    ports:
      - "4200:80"
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.54

volumes:
    postgres-integration:
        driver:
            local
    django-integration:
        driver:
            local
    angular-integration:
        driver:
            local

networks:
  assignment1-network:
    external: true